### ISSUE TITLE
Running 'setHeader' during 'proxyReq' event fails for POST requests

### ISSUE THREAD

**Issue by cdl** [nodejitsu/node-http-proxy#908]
Right now, it looks like trying to do a `setHeader` on the passed in `proxyReq` for `POST` requests fails. (see below:)

```js
proxy.on('proxyReq', function(proxyReq, req, res, options) {
  proxyReq.setHeader('origin', 'https://example.com');
});
```

**Comment by jcrugzz** [comment]
@cdl what node version does this happen in? Could you write a reproducible test case? I want to establish if this is a deterministic issue and if not what conditions FULLY create it. Thanks!

**Comment by cdl** [comment]
@jcrugzz Happens in node `4.2.1`. Will see about stubbing out a reproducible test case for it for sure.

**Comment by jcrugzz** [comment]
@cdl can you upgrade to `node@4.2.2` there was an `http` bug in `4.2.1` that was resolved in the patch version. See if upgrading resolves this one as well. Let me know either way! Thanks

**Comment by cdl** [comment]
@jcrugzz Just tested in `node@4.2.2`, issue still persists. Will write up a gist demonstrating the issue shortly.

**Comment by jcrugzz** [comment]
@cdl sounds good, and if you can encapsulate it into a test that you can PR to this project that would get us closer to a solution :). Thanks for the update!

**Comment by stickystyle** [comment]
I had the same issue after upgrading to 1.12.0, downgrading back to 1.11.3 resolved it for me.

**Comment by jcrugzz** [comment]
@stickystyle could you post a sample of the code that you use for `http-proxy`? This doesn't seem like a bug in `http-proxy` since its part of the `http` semantic so this is very curious

**Comment by stickystyle** [comment]
@jcrugzz I've just made a scrubbed gist of the `app.js` and `package.json` that I'm using. It's a simple proxy that serves to layer JWT and caching on top of a RESTful API.
I too did a compare of the tag to master and didn't see anything that stood out, so it makes me think that one of the `http-proxy` dependencies that got updated is triggering it.

https://gist.github.com/stickystyle/a35fa8bc7461018aad83

**Comment by stickystyle** [comment]
For me, this issue has gone away in the most recent v1.13.2
